export const styles = {
    container: 'p-8',
    header: 'flex flex-row flex-wrap justify-between',
    title: 'text-2xl',
    avatar: 'w-12 h-12 rounded-3xl',
    postar: 'text-4xl text-center my-5 font-bold',
    button: 'p-5 rounded-xl mt-5 border-gray-300 border-2',
    buttonText: 'text-xl text-center',
    inputGroup: 'my-4',
    inputLabel: 'text-sm font-bold my-1',
    input: 'p-2 border-gray-300 border-b-2 rounded-xl pl-1',
    errorMessage: 'text-xl text-red my-2 text-center',
    questionBox: 'bg-orange-100 rounded-xl p-3 my-8',
    questionText: 'font-bold',
    verseBox: 'bg-gray-300 rounded-xl p-2 my-2',
    verseTitle: 'font-bold',
    verseText: 'my-1',
    navigationButtons: 'flex-row justify-between',
    navButton: 'w-36 p-5 rounded-xl mt-5 border-gray-300 border-2',
    navButtonText: 'text-xl text-center',
    page: 'text-center'
    //   questionBox: {
    //     backgroundColor: '#ccc1b4',
    //     borderRadius: 8,
    //     padding: 16,
    //     marginBottom: 16,
    //   },
    //   questionText: {
    //     color: '#444444',
    //     fontWeight: 'bold',
    //   },
    //   verseBox: {
    //     backgroundColor: '#e8ebe9',
    //     borderRadius: 8,
    //     padding: 16,
    //     marginBottom: 8,
    //   },
    //   verseTitle: {
    //     color: '#444444',
    //     fontWeight: 'bold',
    //   },
    //   verseText: {
    //     color: '#444444',
    //     marginTop: 8,
    //   },
    //   navigationButtons: {
    //     flexDirection: 'row',
    //     justifyContent: 'space-between',
    //   },
    //   navButton: {
    //     padding: 12,
    //     backgroundColor: '#444444',
    //     borderRadius: 8,
    //     width: '48%',
    //     alignItems: 'center',
    //   },
    //   navButtonText: {
    //     color: 'white',
    //   },    
};