export const styles = {
    container: 'p-8',
    header: 'flex flex-row flex-wrap justify-between mb-5',
    title: 'text-2xl',
    avatar: 'w-12 h-12 rounded-3xl',
    postar: 'text-4xl text-center my-5 font-bold',
    button: 'px-5 py-2 rounded-xl mt-5 border-gray-300 border-2',
    buttonText: 'text-lg text-center',
    inputGroup: 'my-2 flex-row flex-wrap justify-between',
    inputLabel: 'text-sm font-bold mt-2',
    input: 'p-2 border-gray-300 border-b-2 rounded-xl pl-1',
    errorMessage: 'text-xl text-red my-2 text-center',
    settingContainer: 'flex flex-row justify-between items-center bg-gray-300 p-3 my-3 rounded-xl',
    settingDescription: 'text-lg',
    buttonGroup: 'flex flex-row justify-between w-100',
    about: 'text-2xl my-5',
    aboutButtonText: 'text-md text-center',
    modal: {
        padding: 40,
        paddingTop: 20,
        justifyContent: 'center',  
        backgroundColor : "#f2f2f2",   
        height: 350 ,  
        width: '80%',  
        borderRadius:10,  
        borderWidth: 1,  
        borderColor: '#d1d5db',    
        marginTop: 100,  
        marginLeft: 40,
    },  
};