export const styles = {
    container: 'p-8',
    header: 'flex flex-row flex-wrap justify-between mb-5',
    title: 'text-2xl',
    avatar: 'w-12 h-12 rounded-3xl',
    postar: 'text-4xl text-center my-5 font-bold',
    button: 'px-5 py-3 rounded-xl mt-5 border-gray-300 border-2',
    buttonText: 'text-xl text-center',
    inputGroup: 'my-4',
    inputLabel: 'text-sm font-bold my-1',
    input: 'p-2 border-gray-300 border-b-2 rounded-xl pl-1',
    errorMessage: 'text-xl text-red my-2 text-center',
    settingContainer: 'flex flex-row justify-between items-center bg-gray-300 p-3 my-3 rounded-xl',
    settingDescription: 'text-lg',
    modal: {  
        justifyContent: 'center',  
        alignItems: 'center',   
        backgroundColor : "#00BCD4",   
        height: 300 ,  
        width: '80%',  
        borderRadius:10,  
        borderWidth: 1,  
        borderColor: '#fff',    
        marginTop: 100,  
        marginLeft: 40,
    },  
  };